"""Update Tables

Revision ID: 5084e60744b7
Revises: 521679454977
Create Date: 2026-09-09 12:19:28.241439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5084e60744b7'
down_revision: Union[str, Sequence[str], None] = '521679454977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_constraint(op.f('chunks_document_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_document_id_fkey'), 'chunks', 'documents', ['document_id'], ['id'])
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    # ### end Alembic commands ###
